#!/usr/bin/python
#-*- coding: utf-8 -*-
from sys import argv as arguments
import urban_dictonary.urban_dict as ud

# example betty.py hi

#TODO
#write down all todo here


#for testing comment them when using
print ('Number of arguments:', len(arguments), 'arguments.')
#print ('Argument List:', (arguments))
print('\n')
#for testing ends here
if len(arguments) <= 2:
	print('Hi I am Betty Your command line assistant Still Under Development\n')
	print('''Usage:\nbetty 
	<commands [args]>
	\nCommands:
	\nWhat is [args]: search for definition of args in dictionary
	\nEntries with [args]: search for a word by their respective substring''')
#add help menu above and this should also launch on 0 argvs too 

if (len(arguments) <= 2 and arguments[1] == 'help'):
	print('''Usage:\nbetty 
	<commands [args]>
	\nCommands:
	\nWhat is [args]: search for definition of args in dictionary
	\nEntries with [args]: search for a word by their respective substring''')
# making what is
if len(arguments) >= 4:
	if (arguments[1] == 'what' or arguments[1] == 'What') and arguments[2] == 'is' :
		rest_of_len = len(arguments) - 3 # 1 = betty , 2 = what , 3 = is
#why do i prefer tabs or spaces am i bad ? check google
		word = [] 
		for i in range(rest_of_len):
		  word.append(arguments[3+i])
		ud.urban_dict(' '.join(word)) # like betty.py what is fake news
		# urban_dictonary contains 4500 words in csv file so so so 
	if (arguments[1] == 'entries' or arguments[1] == 'Entries') and arguments[2] == 'with':
		print(arguments[3])
		ud.entries_with(arguments[3])
